config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  root 'hello#index'

  get 'hello/link' => 'hello#link'
  get 'tweets' => 'tweets#index'
  get 'tweets/new' => 'tweets#new'
  post 'tweets' => 'tweets#create'
  get 'tweets/:id' => 'tweets#show',as: 'tweet'
  patch 'tweets/:id' => 'tweets#update'
  delete 'tweets/:id' => 'tweets#destroy'
  get 'tweets/:id/edit' => 'tweets#edit', as:'edit_tweet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  #アソシエーション(1:多)
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション(1:多)
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!

    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
    end

    private
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
      <h1>GeekTwitter</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_path %></li>
        <li><%= link_to "新規投稿",tweets_new_path %></li>
      </ul>
      </div>
    </header>
    <main>
     <%= yield %>
    </main>
    <footer>
     <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<!-- localhost:3000/tweets -->
<!-- localhost:3000/users/sign_up -->

<%= stylesheet_link_tag 'index', :media => "all" %>

<h1>GeekTwitter</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to "新規投稿へ", tweets_new_path %>

<div class="tweets-container">
<h3>Tweet一覧</h3>
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.user.email %>
      <div class="main-box">
        <div class="left-container"><%= t.body %></div>
        <div class="right-container">
          <%= link_to "詳細", tweet_path(t.id) %>
          <%= link_to "編集", edit_tweet_path(t.id) %>
          <%= link_to "削除", tweet_path(t.id), method: :delete %>
        </div>
      </div>
        <p class="time"><%= t.created_at %></p>
    </div>
 <% end %>
</div>

app/views/tweets/new.html.erb
<!-- localhost:3000/tweets/new -->

<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :body,size: 140%>
        <br>
    <%= f.submit "送信"%>
    <br>
    <% end %>
</div>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>